"""
DeckForge Family Catalog
Static registry of all downloadable BIM families + materials.
Paths under rfaFiles are relative to revit_family/ root.
"""

FAMILY_CATALOG = {
    "decking": [
        {
            "id": "ipe_hardwood",
            "name": "IPE Hardwood",
            "brand": "Advantage Lumber",
            "description": "The benchmark tropical hardwood. Extremely dense, naturally rot and insect resistant. 25+ year lifespan.",
            "revitMaterialName": "Advantage Lumber - Ipe",
            "texturePreview": "/static/textures/advantage-lumber/Advantage-Lumber_Hardwood_Ipe_Tile.jpeg",
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": "materials/Advantage_Lumber.adsklib",
            "category": "decking",
        },
        {
            "id": "cumaru_hardwood",
            "name": "Cumaru",
            "brand": "Advantage Lumber",
            "description": "Brazilian teak alternative. Warm golden-brown tones, Janka 3540. Exceptional durability.",
            "revitMaterialName": "Advantage Lumber - Cumaru",
            "texturePreview": "/static/textures/advantage-lumber/Advantage-Lumber_Hardwood_Cumaru_Tile.jpeg",
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": "materials/Advantage_Lumber.adsklib",
            "category": "decking",
        },
        {
            "id": "teak_hardwood",
            "name": "Teak",
            "brand": "Advantage Lumber",
            "description": "Classic premium deck species. High silica content repels water and insects. Ages to silver-grey.",
            "revitMaterialName": "Advantage Lumber - Teak",
            "texturePreview": "/static/textures/advantage-lumber/Advantage-Lumber_Hardwood_Teak_Tile.jpeg",
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": "materials/Advantage_Lumber.adsklib",
            "category": "decking",
        },
        {
            "id": "garapa_hardwood",
            "name": "Garapa",
            "brand": "Advantage Lumber",
            "description": "Brazilian blond wood. Bright honey-gold colour, smooth grain. More affordable than IPE.",
            "revitMaterialName": "Advantage Lumber - Garapa",
            "texturePreview": "/static/textures/advantage-lumber/Advantage-Lumber_Hardwood_Garapa_Tile.jpeg",
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": "materials/Advantage_Lumber.adsklib",
            "category": "decking",
        },
        {
            "id": "tigerwood_hardwood",
            "name": "Tigerwood",
            "brand": "Advantage Lumber",
            "description": "Dramatic orange-brown with dark streaks. Striking visual character, Janka 1850.",
            "revitMaterialName": "Advantage Lumber - Tigerwood",
            "texturePreview": "/static/textures/advantage-lumber/Advantage-Lumber_Hardwood_Tigerwood_Tile.jpeg",
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": "materials/Advantage_Lumber.adsklib",
            "category": "decking",
        },
        {
            "id": "masaranduba_hardwood",
            "name": "Masaranduba",
            "brand": "Advantage Lumber",
            "description": "Bulletwood. Deep reddish-brown, one of the hardest deck species available. Janka 3190.",
            "revitMaterialName": "Advantage Lumber - Masaranduba",
            "texturePreview": "/static/textures/advantage-lumber/Advantage-Lumber_Hardwood_Masaranduba_Tile.jpeg",
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": "materials/Advantage_Lumber.adsklib",
            "category": "decking",
        },
        {
            "id": "golden_mahogany",
            "name": "Golden Mahogany",
            "brand": "Advantage Lumber",
            "description": "Rich warm-brown tones with golden undertones. Excellent workability and natural lustre.",
            "revitMaterialName": "Advantage Lumber - Golden Mahogany",
            "texturePreview": "/static/textures/advantage-lumber/Advantage-Lumber_Hardwood_Golden-Mahogany_Decking.jpeg",
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": "materials/Advantage_Lumber.adsklib",
            "category": "decking",
        },
        {
            "id": "thermowood",
            "name": "ThermoWood",
            "brand": "ThermoWood",
            "description": "Heat-treated Scandinavian pine. Dimensionally stable, zero chemicals. Warm grey-brown tones.",
            "revitMaterialName": "ThermoWood Decking",
            "texturePreview": "/static/textures/thermowood/diffuse.jpg",
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": None,
            "category": "decking",
        },
    ],

    "railings": [
        {
            "id": "newtechwood_composite",
            "name": "NewTechWood Composite",
            "brand": "NewTechWood",
            "description": "WPC composite railing — wood grain look, zero maintenance. UV-stable, 25yr warranty.",
            "revitMaterialName": "",
            "texturePreview": None,
            "rfaFiles": [
                "railings/newtechwoo/NewTechWood_Post.rfa",
                "railings/newtechwoo/NewTechWood_Baluster.rfa",
                "railings/newtechwoo/NewTechWood_Railing-Profile.rfa",
            ],
            "revitComponents": {
                "post":           "NewTechWood_Post",
                "baluster":       "NewTechWood_Baluster",
                "topRailProfile": "NewTechWood_Railing-Profile",
            },
            "adsklib": None,
            "category": "railing",
            "componentCount": 3,
        },
        {
            "id": "ultralox_aluminum",
            "name": "ULTRALOX Aluminum Drink Rail",
            "brand": "ULTRALOX",
            "description": "Aluminum interlocking system with signature drink rail top. Sleek modern profile, powder-coat finish.",
            "revitMaterialName": "",
            "texturePreview": None,
            "rfaFiles": [
                "railings/ultralox/ULTRALOX-Post.rfa",
                "railings/ultralox/ULTRALOX-Post-Juliet.rfa",
                "railings/ultralox/ULTRALOX-Bottom_Rail.rfa",
                "railings/ultralox/ULTRALOX-Mid_Rail.rfa",
                "railings/ultralox/ULTRALOX-Drink_Rail.rfa",
                "railings/ultralox/ULTRALOX-Balusters.rfa",
                "railings/ultralox/ULTRALOX-Support.rfa",
            ],
            "revitComponents": {
                "post":       "ULTRALOX-Post",
                "cornerPost": "ULTRALOX-Post-Juliet",
                "bottomRail": "ULTRALOX-Bottom_Rail",
                "midRail":    "ULTRALOX-Mid_Rail",
                "topRail":    "ULTRALOX-Drink_Rail",
                "balusters":  "ULTRALOX-Balusters",
                "support":    "ULTRALOX-Support",
            },
            "adsklib": None,
            "category": "railing",
            "componentCount": 7,
        },
        {
            "id": "falcon_vinyl_classic",
            "name": "Falcon Vinyl Classic",
            "brand": "Falcon Vinyl",
            "description": "Classic vinyl baluster railing. Bright white, circular handrail. Traditional coastal aesthetic.",
            "revitMaterialName": "",
            "texturePreview": None,
            "rfaFiles": [
                "railings/falcon-vinyl/Baluster_Post.rfa",
                "railings/falcon-vinyl/Bottom Rail.rfa",
                "railings/falcon-vinyl/Top Rail.rfa",
                "railings/falcon-vinyl/Baluster.rfa",
                "railings/falcon-vinyl/Cap.rfa",
                "railings/falcon-vinyl/Circular Handrail.rfa",
                "railings/falcon-vinyl/Fascia-Flat.rfa",
                "railings/falcon-vinyl/Rectangular Handrail.rfa",
                "railings/falcon-vinyl/Spindle.rfa",
                "railings/falcon-vinyl/Fascia-Flat.rfa",
            ],
            "revitComponents": {
                "post":      "Baluster_Post",
                "bottomRail":"Bottom Rail",
                "topRail":   "Top Rail",
                "infill":    "Baluster",
                "handrail":  "Circular Handrail",
                "cap":       "Cap",
                "fascia":    "Fascia-Flat",
            },
            "adsklib": None,
            "category": "railing",
            "componentCount": 10,
        },
        {
            "id": "falcon_vinyl_spindle",
            "name": "Falcon Vinyl Spindle",
            "brand": "Falcon Vinyl",
            "description": "Turned spindle infill variant. Rectangular handrail profile for a craftsman/colonial look.",
            "revitMaterialName": "",
            "texturePreview": None,
            "rfaFiles": [
                "railings/falcon-vinyl/Baluster_Post.rfa",
                "railings/falcon-vinyl/Bottom Rail.rfa",
                "railings/falcon-vinyl/Top Rail.rfa",
                "railings/falcon-vinyl/Spindle.rfa",
                "railings/falcon-vinyl/Cap.rfa",
                "railings/falcon-vinyl/Rectangular Handrail.rfa",
                "railings/falcon-vinyl/Fascia-Flat.rfa",
                "railings/falcon-vinyl/Baluster.rfa",
                "railings/falcon-vinyl/Circular Handrail.rfa",
            ],
            "revitComponents": {
                "post":      "Baluster_Post",
                "bottomRail":"Bottom Rail",
                "topRail":   "Top Rail",
                "infill":    "Spindle",
                "handrail":  "Rectangular Handrail",
                "cap":       "Cap",
                "fascia":    "Fascia-Flat",
            },
            "adsklib": None,
            "category": "railing",
            "componentCount": 9,
        },
    ],

    "pergolas": [
        {
            "id": "no_pergola",
            "name": "No Cover",
            "brand": "",
            "description": "Open deck — full sun exposure, unobstructed sky views.",
            "revitMaterialName": "",
            "texturePreview": None,
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": None,
            "category": "pergola",
        },
        {
            "id": "serenity_irp",
            "name": "Serenity IRP Panel",
            "brand": "Outdoor Elements",
            "description": "Insulated roof panel system. Full weatherproof cover with clean aluminium soffits.",
            "revitMaterialName": "",
            "texturePreview": None,
            "rfaFiles": [
                "pergolas/Outdoor_Elements_Column.rfa",
                "pergolas/Serenity_IRP_Panel_Roof.rfa",
            ],
            "revitComponents": {
                "column": "Louvered-Canopies_Outdoor-Elements_Column",
                "roof":   "Panel-Canopies_Outdoor-Elements_Serenity-Pergola-IRP-Panel-Roof",
            },
            "adsklib": "materials/Outdoor_Elements.adsklib",
            "category": "pergola",
        },
        {
            "id": "signature_louvered",
            "name": "Signature Single Louvered",
            "brand": "Outdoor Elements",
            "description": "Motorised adjustable louvres. Control sun, shade and rain. Single-pitch configuration.",
            "revitMaterialName": "",
            "texturePreview": None,
            "rfaFiles": [
                "pergolas/Outdoor_Elements_Column.rfa",
                "pergolas/Signature_Single_Louvered_Roof.rfa",
            ],
            "revitComponents": {
                "column": "Louvered-Canopies_Outdoor-Elements_Column",
                "roof":   "Louvered-Canopies_Outdoor-Elements_Signature-Louvered-Roof-Single",
            },
            "adsklib": "materials/Outdoor_Elements.adsklib",
            "category": "pergola",
        },
        {
            "id": "solace_louvered",
            "name": "Solace Dual Louvered",
            "brand": "Outdoor Elements",
            "description": "Premium dual-pitch louvred canopy. Ideal for large spans. Integrated lighting option.",
            "revitMaterialName": "",
            "texturePreview": None,
            "rfaFiles": [
                "pergolas/Outdoor_Elements_Column.rfa",
                "pergolas/Solace_Dual_Louvered_Roof.rfa",
            ],
            "revitComponents": {
                "column": "Louvered-Canopies_Outdoor-Elements_Column",
                "roof":   "Louvered-Canopies_Outdoor-Elements_Solace-Louvered-Roof-Dual",
            },
            "adsklib": "materials/Outdoor_Elements.adsklib",
            "category": "pergola",
        },
    ],

    "ceiling": [
        {
            "id": "open_ceiling",
            "name": "Open / None",
            "brand": "",
            "description": "No ceiling treatment — exposed structure or clear sky.",
            "revitMaterialName": "",
            "texturePreview": None,
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": None,
            "category": "ceiling",
        },
        {
            "id": "timber_slat",
            "name": "Timber Slat",
            "brand": "",
            "description": "Horizontal timber slat ceiling. Warm, natural underside. Teak material finish.",
            "revitMaterialName": "Wood - Teak",
            "texturePreview": None,
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": None,
            "category": "ceiling",
        },
        {
            "id": "white_painted_timber",
            "name": "White Painted Timber",
            "brand": "",
            "description": "Painted tongue-and-groove timber ceiling. Clean, bright, Hamptons-coastal aesthetic.",
            "revitMaterialName": "Paint - White",
            "texturePreview": None,
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": None,
            "category": "ceiling",
        },
        {
            "id": "corrugated_steel",
            "name": "Corrugated Steel",
            "brand": "",
            "description": "Industrial corrugated metal ceiling. Modern contrast against timber deck and railings.",
            "revitMaterialName": "Metal - Corrugated",
            "texturePreview": None,
            "rfaFiles": [],
            "revitComponents": {},
            "adsklib": None,
            "category": "ceiling",
        },
    ],
}

# Flat lookup by id across all categories
_FLAT: dict = {}
for _cat, _entries in FAMILY_CATALOG.items():
    for _e in _entries:
        _FLAT[_e["id"]] = _e

def get_entry(entry_id: str) -> dict | None:
    return _FLAT.get(entry_id)
